### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by mendrugory** [joearms/courses#1]
The _Mail_ file has a link which contains all the necessary things to follow the course, but the link is wrong.

It should be: [https://github.com/joearms/courses/blob/master/1_day/Mail](https://github.com/joearms/courses/blob/master/1_day/Mail)

**Comment by joearms** [comment]
You're right - I've fixed it

thanks

/Joe

**Comment by joearms** [comment]
fixed

**Comment by joearms** [comment]
fixed
